# Generated by Django 3.2.5 on 2021-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_page',
            name='fitness_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal_page',
            name='nutrition_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal_page',
            name='productivity_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal_page',
            name='sleep_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal_page',
            name='social_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='extra_resp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='fitness_resp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='nutrition_resp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='productivity_resp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='sleep_resp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal_page',
            name='social_resp',
            field=models.TextField(blank=True),
        ),
    ]
