# Generated by Django 3.2.5 on 2021-08-26 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20210825_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_page',
            name='stress_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
